const express=require('express');
const router=express.Router();
const {addBill,editBill,getBills,updateBillStatus,deleteBill,updateFlagStatus, massUpdateBillStatus,reverseMassBillStatus}=require('../controller/bill');
const authMiddleware = require('../middleware/authMiddleware');
router.post('/addBill',authMiddleware,addBill);
router.put('/editBill/:billId',authMiddleware,editBill);
router.get("/getBills",getBills);
router.put('/updateBillStatus',authMiddleware,updateBillStatus);
router.put('/updateFlagStatus',authMiddleware,updateFlagStatus);
router.put('/massUpdateBillStatus',authMiddleware,massUpdateBillStatus);
router.put('/reverseMassBillStatus',authMiddleware,reverseMassBillStatus);
router.delete(`/bill/:billId`,authMiddleware,deleteBill);
module.exports=router;  